### PR TITLE
do not add empty filename to `files` in `preprocess()`

### PR DESCRIPTION
**Pull request by firewave**

### CODE REVIEW

**Comment by firewave** [comment]
Required for https://github.com/danmar/cppcheck/pull/6326.

Not sure if a test can be written for this.

**Comment by firewave** [comment]
Made a draft because the downstream PR which is built upon these changes fails.

**Comment by firewave** [comment]
> Made a draft because the downstream PR which is built upon these changes fails.

Turns out that it was a fluke.

**Review by danmar — APPROVED** [review]

**Comment by firewave** [comment]
I will still add a unit test for this.

**Pull request merged**
